# Generated by Django 5.1.15 on 2026-08-27 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location_name', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lng', models.FloatField(blank=True, null=True)),
                ('pickup_location_name', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField(blank=True, null=True)),
                ('pickup_location_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_location_name', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_location_lng', models.FloatField(blank=True, null=True)),
                ('current_cycle_used', models.FloatField(default=0.0, help_text='Current cumulative on-duty cycle hours used prior to this trip (0-70)')),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_duration_hours', models.FloatField(default=0.0)),
                ('driving_time_hours', models.FloatField(default=0.0)),
                ('rest_time_hours', models.FloatField(default=0.0)),
                ('total_trip_days', models.IntegerField(default=1)),
                ('is_legal', models.BooleanField(default=True)),
                ('hos_status_summary', models.TextField(blank=True, default='')),
                ('route_geometry', models.JSONField(blank=True, default=list, help_text='Encoded polyline coordinates [[lat, lng], ...]')),
                ('driver_name', models.CharField(default='John E. Doe', max_length=150)),
                ('carrier_name', models.CharField(default='Apex Logistics Express LLC', max_length=200)),
                ('carrier_address', models.CharField(default='100 Freight Way, Chicago, IL 60607', max_length=255)),
                ('home_terminal_address', models.CharField(default='100 Freight Way, Chicago, IL 60607', max_length=255)),
                ('truck_number', models.CharField(default='TRK-7042', max_length=50)),
                ('trailer_number', models.CharField(default='TRL-5309', max_length=50)),
                ('co_driver_name', models.CharField(blank=True, default='', max_length=150)),
                ('shipping_doc_number', models.CharField(default='BOL-884920', max_length=100)),
                ('commodity', models.CharField(default='General Freight / Electronics', max_length=150)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('home_terminal_tz', models.CharField(default='America/Chicago', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_sequence', models.PositiveIntegerField(default=1)),
                ('stop_type', models.CharField(choices=[('CURRENT', 'Current Location / Departure'), ('PICKUP', 'Pickup Location (1 hr On-Duty)'), ('DROPOFF', 'Dropoff Location (1 hr On-Duty)'), ('FUEL', 'Fuel Stop'), ('REST_10H', '10-Hour Mandatory Rest (Sleeper/Off-Duty)'), ('REST_34H', '34-Hour Restart (Sleeper/Off-Duty)'), ('BREAK_30M', '30-Minute Rest Break'), ('COMBINED', 'Combined Fuel & Rest Break')], default='CURRENT', max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('distance_from_last_stop_miles', models.FloatField(default=0.0)),
                ('odometer_miles', models.FloatField(default=0.0)),
                ('reason', models.TextField(help_text='Detailed explanation of why this stop was scheduled')),
                ('hos_impact', models.CharField(blank=True, default='', max_length=255)),
                ('is_optimized', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['stop_sequence'],
            },
        ),
        migrations.CreateModel(
            name='DutyPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('duty_status', models.CharField(choices=[('OFF_DUTY', '1. Off Duty'), ('SLEEPER_BERTH', '2. Sleeper Berth'), ('DRIVING', '3. Driving'), ('ON_DUTY_NOT_DRIVING', '4. On Duty (Not Driving)')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_periods', to='trips.trip')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('log_date', models.DateField()),
                ('total_miles_today', models.FloatField(default=0.0)),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_berth_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_not_driving_hours', models.FloatField(default=0.0)),
                ('total_day_hours', models.FloatField(default=24.0)),
                ('cycle_hours_today', models.FloatField(default=0.0)),
                ('cycle_hours_7day', models.FloatField(default=0.0)),
                ('cycle_hours_8day', models.FloatField(default=0.0)),
                ('cycle_hours_available_tomorrow', models.FloatField(default=70.0)),
                ('duty_segments', models.JSONField(default=list, help_text='List of [{status: str, start_hour: float, end_hour: float, duration: float, location: str}]')),
                ('remarks', models.JSONField(default=list, help_text='List of [{time_str: str, hour: float, status: str, location: str, note: str}]')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
