# Generated by Django 5.1.15 on 2026-08-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
