/**
 * pdfExport.ts
 * Exports ELD log SVGs to individual PDFs or a full-trip PDF report.
 */
import jsPDF from 'jspdf'
import type { TripPlanResponse } from '../types/trip'

/**
 * Export a single SVG element as a PDF page.
 */
export async function exportSingleLogPDF(
  svgRef: SVGSVGElement,
  filename: string = 'eld-log.pdf'
): Promise<void> {
  const canvas = await svgToCanvas(svgRef)
  const imgData = canvas.toDataURL('image/png', 1.0)
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' })
  const pw = pdf.internal.pageSize.getWidth()
  const ph = pdf.internal.pageSize.getHeight()
  pdf.addImage(imgData, 'PNG', 5, 5, pw - 10, ph - 10)
  pdf.save(filename)
}

/**
 * Export all daily logs as a full-trip PDF report (one log per page).
 */
export async function exportFullTripPDF(
  logRefs: SVGSVGElement[],
  trip: TripPlanResponse
): Promise<void> {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' })
  const pw = pdf.internal.pageSize.getWidth()
  const ph = pdf.internal.pageSize.getHeight()

  // ── Cover page ─────────────────────────────────────────────────────────────
  pdf.setFillColor(15, 23, 42) // #0f172a
  pdf.rect(0, 0, pw, ph, 'F')

  pdf.setTextColor(248, 250, 252)
  pdf.setFontSize(24)
  pdf.setFont('helvetica', 'bold')
  pdf.text('SPOTTER', pw / 2, 30, { align: 'center' })

  pdf.setFontSize(12)
  pdf.setFont('helvetica', 'normal')
  pdf.setTextColor(148, 163, 184)
  pdf.text('HOS Route Planner · Full Trip Report', pw / 2, 40, { align: 'center' })

  pdf.setDrawColor(30, 58, 95)
  pdf.setLineWidth(0.5)
  pdf.line(20, 45, pw - 20, 45)

  const infoItems = [
    ['Driver', trip.driver_name || 'N/A'],
    ['Carrier', trip.carrier_name || 'N/A'],
    ['From', trip.current_location_name],
    ['Pickup', trip.pickup_location_name],
    ['Dropoff', trip.dropoff_location_name],
    ['Total Distance', `${trip.total_distance_miles.toFixed(0)} miles`],
    ['Total Duration', `${trip.total_duration_hours.toFixed(1)} hours`],
    ['Total Days', `${trip.total_trip_days} days`],
    ['HOS Status', trip.is_legal ? '✓ LEGAL' : '⚠ REQUIRES ADJUSTMENT'],
    ['Departure', new Date(trip.departure_time).toLocaleString()],
    ['Shipping Doc', trip.shipping_doc_number || 'N/A'],
    ['Commodity', trip.commodity || 'N/A'],
  ]

  pdf.setFontSize(10)
  let infoY = 55
  for (const [label, value] of infoItems) {
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(100, 116, 139)
    pdf.text(label + ':', 30, infoY)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(226, 232, 240)
    pdf.text(String(value), 90, infoY)
    infoY += 8
  }

  pdf.setFontSize(8)
  pdf.setTextColor(71, 85, 105)
  pdf.text(
    `Generated by Spotter HOS Route Planner · FMCSA 49 CFR § 395 · ${new Date().toISOString().split('T')[0]}`,
    pw / 2,
    ph - 8,
    { align: 'center' }
  )

  // ── Daily log pages ─────────────────────────────────────────────────────────
  for (const svgEl of logRefs) {
    const canvas = await svgToCanvas(svgEl)
    const imgData = canvas.toDataURL('image/png', 1.0)
    pdf.addPage('letter', 'landscape')
    pdf.setFillColor(15, 23, 42)
    pdf.rect(0, 0, pw, ph, 'F')
    pdf.addImage(imgData, 'PNG', 5, 5, pw - 10, ph - 10)
  }

  // ── HOS Summary page ────────────────────────────────────────────────────────
  pdf.addPage('letter', 'landscape')
  pdf.setFillColor(15, 23, 42)
  pdf.rect(0, 0, pw, ph, 'F')

  pdf.setTextColor(248, 250, 252)
  pdf.setFontSize(16)
  pdf.setFont('helvetica', 'bold')
  pdf.text('HOS Compliance Summary', pw / 2, 20, { align: 'center' })

  pdf.setDrawColor(30, 58, 95)
  pdf.line(20, 24, pw - 20, 24)

  const { hos_summary } = trip
  const summaryItems = [
    ['Status', hos_summary.is_legal ? '✓ LEGAL — No violations detected' : '⚠ REQUIRES ADJUSTMENT'],
    ['Cycle Hours at Start', `${hos_summary.current_cycle_used.toFixed(1)}h used of 70h`],
    ['Cycle Hours Available (Start)', `${hos_summary.cycle_hours_available_start.toFixed(1)}h`],
    ['Total Cycle Hours Consumed', `${hos_summary.total_cycle_hours_consumed.toFixed(1)}h`],
    ['Cycle Hours Remaining (End)', `${hos_summary.cycle_hours_remaining_end.toFixed(1)}h`],
    ['34h Restart Required', hos_summary.required_34h_restart ? `Yes (Day ${hos_summary.restart_day})` : 'No'],
    ['Driving Hours Remaining (Day 1)', `${hos_summary.driving_hours_remaining_day1.toFixed(1)}h`],
    ['Window Hours Remaining (Day 1)', `${hos_summary.window_hours_remaining_day1.toFixed(1)}h`],
  ]

  pdf.setFontSize(10)
  let sumY = 35
  for (const [label, value] of summaryItems) {
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(100, 116, 139)
    pdf.text(label + ':', 20, sumY)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(226, 232, 240)
    pdf.text(String(value), 110, sumY)
    sumY += 9
  }

  if (hos_summary.violations?.length > 0) {
    sumY += 5
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(239, 68, 68)
    pdf.text('Violations:', 20, sumY)
    sumY += 8
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(9)
    for (const v of hos_summary.violations) {
      pdf.text(`• ${v}`, 25, sumY)
      sumY += 7
    }
  }

  if (hos_summary.explanations?.length > 0) {
    sumY += 5
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(96, 165, 250)
    pdf.text('Compliance Notes:', 20, sumY)
    sumY += 8
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(148, 163, 184)
    pdf.setFontSize(8)
    for (const e of hos_summary.explanations.slice(0, 8)) {
      pdf.text(`• ${e}`, 25, sumY)
      sumY += 7
    }
  }

  pdf.save(`spotter-trip-report-${trip.id || 'export'}.pdf`)
}

// ── Helper: SVG element → canvas ───────────────────────────────────────────────
async function svgToCanvas(svgEl: SVGSVGElement): Promise<HTMLCanvasElement> {
  // Serialize the SVG
  const serializer = new XMLSerializer()
  const svgStr = serializer.serializeToString(svgEl)
  const blob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' })
  const url = URL.createObjectURL(blob)

  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => {
      const canvas = document.createElement('canvas')
      const scale = 3 // high-res
      canvas.width = img.width * scale
      canvas.height = img.height * scale
      const ctx = canvas.getContext('2d')!
      ctx.scale(scale, scale)
      ctx.fillStyle = '#0f172a'
      ctx.fillRect(0, 0, img.width, img.height)
      ctx.drawImage(img, 0, 0)
      URL.revokeObjectURL(url)
      resolve(canvas)
    }
    img.onerror = reject
    img.src = url
  })
}
